version: '2'
services:
  jenkins:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}
    container_name: ${CONTAINER_NAME}
    hostname: ${CONTAINER_NAME}
    restart: always
    ports:
      - "8080:8080" 
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins:
